.\" $Header: /home/disk/atmos/CVSROOT/ive/mnemosyne/mnemalyse.1,v 1.1.1.1 1993/04/07 19:41:28 harry Exp $
.TH MNEMALYSE 1
.SH NAME
mnemalyse \- analyse dynamic memory allocation statistics
.SH SYNTAX
.B mnemalyse
.SH DESCRIPTION
.I Mnemalyse
interprets mnemosyne pointer and symbol databases and prints
statistics about dynamically allocated data that was not freed.
The program expects to find the files
.I "mnem.syms"
and
.I "mnem.dat"
in the current working directory.
There are no options and the output is self-explanatory:
.IP
.nf
hussar-> mnemalyse
922 bytes missing mtest.c line:19
123 bytes missing mtest.c line:20
1 bytes missing mtest.c line:27
2 bytes missing mtest.c line:27
3 bytes missing mtest.c line:27
4 bytes missing mtest.c line:27
5 bytes missing mtest.c line:27
6 bytes missing mtest.c line:27
9 pointers, 8 lost totalling 1066 bytes
.fi
.SH FILES
.ta 25n
mnem.syms	Source code line number map
.br
mnem.dat	Pointer allocation map
.SH SEE ALSO
.IR mnemosyne (3)
.SH AUTHOR
Marcus J. Ranum (mjr@decuac.dec.com)
